/**
 * Title: Tab2 Page - Add New Item & Featured Items
 * Author: Ma Xinrui and Hao Wang
 * Student ID: 24832562 and 24832782
 * Description: This page allows users to add new inventory items
 * and display items marked as featured.
 */

import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { 
  IonHeader, IonToolbar, IonTitle, IonContent, IonCard, IonCardHeader, 
  IonCardTitle, IonCardContent, IonItem, IonInput, IonSelect, 
  IonSelectOption, IonCheckbox, IonTextarea, IonButton, IonList, 
  IonLabel, IonBadge, IonIcon, IonNote, IonText,
  AlertController, ToastController, LoadingController 
} from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import { star, pricetag, helpCircleOutline } from 'ionicons/icons';
import { InventoryService } from '../services/inventory';
import { InventoryItem } from '../models/inventory.model';

@Component({
  selector: 'app-tab2',
  templateUrl: 'tab2.page.html',
  styleUrls: ['tab2.page.scss'],
  standalone: true,
  // 将所有用到的组件逐一列出
  imports: [
    CommonModule, ReactiveFormsModule,
    IonHeader, IonToolbar, IonTitle, IonContent, IonCard, IonCardHeader, 
    IonCardTitle, IonCardContent, IonItem, IonInput, IonSelect, 
    IonSelectOption, IonCheckbox, IonTextarea, IonButton, IonList, 
    IonLabel, IonBadge, IonIcon, IonNote, IonText
  ]
})
export class Tab2Page implements OnInit {
  public featuredItems: InventoryItem[] = [];
  public categories = ['Electronics', 'Furniture', 'Clothing', 'Tools', 'Miscellaneous'];
  public stockStatuses = ['In Stock', 'Low Stock', 'Out of Stock'];
  public addForm: FormGroup;

  constructor(
    private fb: FormBuilder,
    private inventoryService: InventoryService,
    private alertController: AlertController,
    private toastController: ToastController,
    private loadingController: LoadingController
  ) {
    addIcons({ star, pricetag, helpCircleOutline });

    // 自定义验证器：禁止商品名包含数字
    const noNumbersValidator = (control: any) => {
      const hasNumbers = /\d/.test(control.value);
      return hasNumbers ? { hasNumbers: true } : null;
    };

    
    this.addForm = this.fb.group({
      item_name: ['', [Validators.required, Validators.minLength(2), noNumbersValidator]],      category: ['', Validators.required],
      quantity: [null, [Validators.required, Validators.min(1)]],
      price: [null, [Validators.required, Validators.min(0)]],
      supplier_name: ['', Validators.required],
      stock_status: ['', Validators.required],
      featured_item: [false],
      special_note: ['']
    });
  }

  ngOnInit(): void {
    this.loadFeaturedItems();
  }

  ionViewWillEnter() {
    this.loadFeaturedItems();
  }

  loadFeaturedItems(): void {
    this.inventoryService.getAllItems().subscribe({
      next: (data: InventoryItem[]) => {
        this.featuredItems = data.filter(item => Number(item.featured_item) === 1);
      },
      error: (err: any) => console.error('Error loading items:', err)
    });
  }

  async addNewItem(): Promise<void> {
    if (this.addForm.invalid) {
// 检查具体的验证错误
      if (this.addForm.get('item_name')?.errors?.['hasNumbers']) {
        this.showToast('Item name cannot contain numbers', 'warning');
      } else {
        this.showToast('Please fill all required fields', 'warning');
      }      return;
    }

    const loading = await this.loadingController.create({ message: 'Validating...' });
    await loading.present();

    const formData = this.addForm.value;
    const newName = formData.item_name.trim();

    // 名称唯一性校验
    this.inventoryService.getAllItems().subscribe({
      next: (items: InventoryItem[]) => {
        const isDuplicate = items.some(i => i.item_name.toLowerCase() === newName.toLowerCase());
        
        if (isDuplicate) {
          loading.dismiss();
          this.showToast('Error: This item name already exists!', 'danger');
          return;
        }

        // 基于当前时间戳，保证唯一性和自增感
        const autoGeneratedId = Math.floor(Date.now() / 1000);

        const finalData: InventoryItem = {
          ...formData,
          item_id: autoGeneratedId, // 保证数据完整性
          quantity: Number(formData.quantity),
          price: Number(formData.price),
          featured_item: formData.featured_item ? 1 : 0
        };

        // 执行创建
        this.inventoryService.createItem(finalData).subscribe({
          next: () => {
            loading.dismiss();
            this.showToast('Item added successfully!', 'success');
            this.addForm.reset({ featured_item: false });
            this.loadFeaturedItems();
          },
          error: (err) => {
            loading.dismiss();
            this.showToast('Add failed: ' + err.message, 'danger');
          }
        });
      },
      error: () => {
        loading.dismiss();
        this.showToast('Network error, please try again.', 'danger');
      }
    });
  }

  async showHelp() {
    const alert = await this.alertController.create({
      header: 'Tab 2 Help Guide',
      message: 'Complete the form to add a new inventory item. Required fields are marked with *.',
      buttons: ['OK']
    });
    await alert.present();
  }

  async showToast(message: string, color: string) {
    const toast = await this.toastController.create({
      message,
      duration: 2500,
      color: color as any,
      position: 'bottom'
    });
    await toast.present();
  }
}